services:
  backend:
    build:
      context: .
    container_name: healthcare-backend
    ports:
      - "4000:4000"
    environment:
      PORT: 4000
      MONGO_URI: mongodb://mongo:27017/healthcare_db
      JWT_SECRET: supersecretkey
    depends_on:
      - mongo
    restart: unless-stopped

  frontend:
    build:
      context: ./healthcare-frontend
    container_name: healthcare-frontend
    ports:
      - "4173:4173"
    depends_on:
      - backend
    restart: unless-stopped

  mongo:
    image: mongo:7
    container_name: healthcare-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data: